arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  root_name: joint1_base # <--- 로봇의 시작 링크
  tip_name: mounting_plate      # <--- 로봇의 끝 링크